// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/*void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}*/

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADwNE28zLa5WMo7o4QFJB1XNRTvJI8JeM',
    appId: '1:599671506042:web:6727ed78ec38a474fe67c3',
    messagingSenderId: '599671506042',
    projectId: 'perwira-store',
    authDomain: 'perwira-store.firebaseapp.com',
    databaseURL: 'https://perwira-store-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perwira-store.appspot.com',
    measurementId: 'G-EXHV98JPJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMTpON0vRAv5-6vNlXYe2PYhSPfFkz89s',
    appId: '1:599671506042:android:03f8e52f9e5ac74afe67c3',
    messagingSenderId: '599671506042',
    projectId: 'perwira-store',
    databaseURL: 'https://perwira-store-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perwira-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChu-SbCG_R46hnirlox7QTUBPaZ3IgMcI',
    appId: '1:599671506042:ios:6e94229db882138bfe67c3',
    messagingSenderId: '599671506042',
    projectId: 'perwira-store',
    databaseURL: 'https://perwira-store-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perwira-store.appspot.com',
    iosBundleId: 'com.example.perwirastoremanage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChu-SbCG_R46hnirlox7QTUBPaZ3IgMcI',
    appId: '1:599671506042:ios:6e94229db882138bfe67c3',
    messagingSenderId: '599671506042',
    projectId: 'perwira-store',
    databaseURL: 'https://perwira-store-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perwira-store.appspot.com',
    iosBundleId: 'com.example.perwirastoremanage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADwNE28zLa5WMo7o4QFJB1XNRTvJI8JeM',
    appId: '1:599671506042:web:6a88c2e479e13ae2fe67c3',
    messagingSenderId: '599671506042',
    projectId: 'perwira-store',
    authDomain: 'perwira-store.firebaseapp.com',
    databaseURL: 'https://perwira-store-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perwira-store.appspot.com',
    measurementId: 'G-ETV42XP2YB',
  );

}